[package]
name = "log-guard"
version = "0.1.0"
edition = "2021" # 

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.100"
chrono = "0.4.31"